### ISSUE TITLE
Xcaped key behaviour when shifted

### ISSUE THREAD

**Issue by forgetmenotz** [alols/xcape#119]
The xcaped key when shifted produces the shifted keysym, but it is followed by the xcape character (as expected I suppose?) on key release. 

However I wanted it to produce only the shifted keysym when shifting it. E.g. I wanted to use the capslock key as Mode_switch when holding, Return on keyup and BackSpace when shifted.

Is there any way that this might be achieved?

Mode_switch characters also fail often when using capslock key. But not an xcape issue...

Nevermind, I realised someone already made a fix for this.

**Comment by adamtabrams** [comment]
@forgetmenotz Please post a link to the fix that you found. I'm having the same issue.

**Comment by adamtabrams** [comment]
I found the fix that the OP was referring to: PR https://github.com/alols/xcape/pull/84

I'm not sure why this wasn't added to the project. It adds very little code, no extra dependencies, it's backwards compatible, and it makes xcape more useful.

@alols Is there any reason why this didn't make it into the project?
