### ISSUE TITLE
Beginner questions, how to remove/reset settings?

### ISSUE THREAD

**Issue by jtv199** [alols/xcape#126]
I have used `xcape -e 'Alt_L=#41'` to test out the functionality and then used `xcape -e 'Alt_L=space'` thinking it would overide the previous instruction, though now when i tap LAlt it just prints both assignments. Is there a way i can reset or remove this?

**Comment by danr** [comment]
I think the way is to kill the processes and just start a new one. Terminating them can be done in many ways such as `pkill 
xcape` or `killall xcape`.

**Comment by jtv199** [comment]
Thanks, that was it. It seems like I should learn more bash.
