### ISSUE TITLE
[SOLVED] Mapping CapsLock to Control_R when pressed and Esc when pressed once 

### ISSUE THREAD

**Issue by zenny** [alols/xcape#129]
Hi,

I could successfully map CapsLock to Super_R when pressed and Esc when pressed and released at once with the follwoing:

```
xset r rate 300 50
setxkbmap -layout eu,us -option grp:alt_space_toggle,caps:super
killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape'
xmodmap -e 'keycode 135 = Super_R'
```

However, when I tried to map CapsLock to Control_R when pressed and Esc when pressed and released at once does NOT work with the following:

```
xset r rate 300 50
setxkbmap -layout eu,us -option grp:alt_space_toggle,caps:ctrl_modifier
killall xcape 2>/dev/null ; xcape -e 'Control_R=Escape'
xmodmap -e 'keycode 105 = Control_R'
```
What did I miss? Any clue appreciated. Cheers,

**Comment by rafaeln** [comment]
I gave up on using `xcape` to try and do that on Ubuntu 18.04 i3wm and have since happily switched to [ctrl2esc](https://gitlab.com/grimmware/ctrl2esc/).

**Comment by zenny** [comment]
> I gave up on using `xcape` to try and do that on Ubuntu 18.04 i3wm and have since happily switched to [ctrl2esc](https://gitlab.com/grimmware/ctrl2esc/).

Thanks. I do not use Ubuntu myself . Currently on  Voidlinux. I liked https://gitlab.com/interception/linux/plugins/dual-function-keys, but went with a working approach. 

I did the following and it worked:

```
xset r rate 300 50
setxkbmap -layout eu,us -option grp:alt_space_toggle,caps:ctrl_modifier
killall xcape 2>/dev/null ; xcape -e 'Control_L=Escape'
xmodmap -e 'keycode 66 = Control_L'
```

Maybe this is helpful to someone. Cheers,
