### ISSUE TITLE
Is it possible to send key sequences on a single key stroke?

### ISSUE THREAD

**Issue by QiangF** [alols/xcape#41]
Hi,
This perhaps is not appropriate to be called an issure. But it looks like we can only send a combination of keys once. I am using emacs, can I send a key sequence like "ctrl-x" then "alt-o" (which toggles omit mode in dired) for a short hit of the shift key?  Sure we can bind the command to a key with modifier,  but in emacs a single key with modifier is quite scarce resource.
Thank you very much!

**Comment by alols** [comment]
No, you need to solve this in your emacs config.
