### ISSUE TITLE
xcape stopps working after suspend

### ISSUE THREAD

**Issue by pipapu** [alols/xcape#43]
I followed instructions to make <space> work at control key if pressed with other key. It's great, but only until the next suspend (closing, opening the laptop under Ubuntu). I suspect there is hook somewhere, where I can put my space-as-ctrl.sh command in to call it after every suspend. 
Of course, there are the /etc/pm/sleep.d/ hooks, but they are not userspace (and might not even find the Xorg process). Is there a recommended solution?

**Comment by alols** [comment]
Could you try to find out if it is because xcape crashes or something else?

**Comment by pipapu** [comment]
xcape does not crash. Using ps, I see it before and after a suspend, while the space-as-ctrl.sh functionality disappears.

**Comment by alols** [comment]
If you are using xmodmap and Ubuntu that is your problem. [See here](http://askubuntu.com/questions/325272/permanent-xmodmap-in-ubuntu-13-04).

**Comment by pipapu** [comment]
Right, this seems to be the problem. Tried to work around it by putting a script into /etc/pm/sleep.d/, but can't get it to work after a real suspend (it works when run as `sudo /etc/pm/sleep.d/90_space-as-ctrl resume`). I'll give up on this.

**Comment by shanesmith** [comment]
For anyone else who ends up here searching for an fix, here's what worked for me on Ubuntu 14.04 using setxkbmap.

Open dconf-editor (`apt-get install dconf-editor` if you don't have it) and navigate to org > gnome > desktop > input sources, then set your setxkbmap options in `xkb-options` as a list.

For example, to set caps lock as a ctrl modifier I've set it to `['caps:ctrl_modifier']`.

(source: http://askubuntu.com/questions/410499/make-setxkbmap-preferences-being-set-at-startup)
