### ISSUE TITLE
Using xcape sets keymap to US temporarily

### ISSUE THREAD

**Issue by KoltPenny** [alols/xcape#46]
Hi,

I normally use a spanish keyboard so the special keys are arranged in a different way.
I have the following setup for the Super key:
xcape -e 'Super_L=Super_L|D'
Super+D is a prefix command in my WM so after it I can press other keys and get different options, the problem is, whenever I hit the "?" key I get a "/", making xcape useless. Is there a way to fix this?

**Comment by alols** [comment]
Hi, I can't reproduce this problem, so it is probably not xcape that is the culprit. Also I looked at the Spanish keyboard layout, and the position of `?` there is not the same as the position of `/` on a US keyboard.

**Comment by Gionson13** [comment]
I have a similar problem:
In my keyboard settings, I have set alt+f1 as a shortcut for rofi. I also set the super key as alt+f1:
```
xcape -e 'Super_L=Alt_L|F1;Super_R=Alt_L|F1'
```

Hoverver if i use alt+f1, i get rofi with the right keyboard layout (I use fr_CH, qwertz), but if I use the super key, I get a qwerty layout.

I use arch linux with xfce.
