### ISSUE TITLE
"-t" Flag Not Using Default

### ISSUE THREAD

**Issue by yahooguntu** [alols/xcape#50]
Not a big issue, but if you specify the "-t" flag without giving a value, the program chokes. I'm running the following command:

xcape -d -t -e "Mode_switch=Escape"

It says "Mode_switch=Escape" isn't a command line option, so it appears the "-t" is consuming "-e" as the timeout delay, leaving the "Mode_switch..." clause stranded.

**Comment by ooesili** [comment]
I feel like that is how it's supposed to work. What exactly are you trying to accomplish? Does this not work?

```
xcape -d -e "Mode_switch=Escape"
```
