### ISSUE TITLE
Cannot bind Caps_Lock to a key

### ISSUE THREAD

**Issue by schyzophrene-asynchrone** [alols/xcape#55]
I cannot today bind my left shift to the capslock key.
It used to work, but I now get this error:
~~~~~
WARNING: No keycode found for keysym Caps_Lock (0xffe5) in mapping Shift_L. Ignoring this mapping.
~~~~~
I precise I use the X11 option "caps:backspace".
I don't have any other information and I'm quite unfamiliar with X11 and its configuration (I'm only able to choose which options I prefer…)

**Comment by dilutedh2o** [comment]
Why was this closed? I have exactly the same issue and have no idea how to resolve.

**Comment by maplepy** [comment]
ask @alols
