### ISSUE TITLE
TTY?

### ISSUE THREAD

**Issue by krompus** [alols/xcape#63]
I realise that it's outside of the scope of this program, but I have become addicted to having Ctrl/Escape on the CapsLock key, and I'm wondering if anyone here knows of a way to get this behaviour without X.

:P

**Comment by vyp** [comment]
If it helps, it [seems like](https://www.emacswiki.org/emacs/MovingTheCtrlKey#toc7) it's possible to have at least control key in place of caps lock. But I have no idea about making it Ctrl/Escape. But remember, `Ctrl-[` is a good backup way to press escape after you've done that (assuming your keyboard layout has `[` key reasonably accessible).

**Comment by Wildefyr** [comment]
`Ctrl-c` will also work to a degree. There is a difference though, [see here](https://stackoverflow.com/questions/5030164/whats-the-difference-between-ctrlc-and-ctrl)

**Comment by krompus** [comment]
@vyp haha, I just found that same page this evening. I'll try to train myself to use `Ctrl-[` in the TTY, thanks!
