### ISSUE TITLE
Feature Request: Do not send escape event if the mouse is clicked while holding the key.

### ISSUE THREAD

**Issue by minego** [alols/xcape#66]
If I press control, click with the mouse, and then release it the mouse event will work as a control+click AND an escape keypress will be sent. I would like a mouse click to be treated like another keypress, and prevent sending escape.

This is not a huge problem, but in some applications that use control+click it can cause confusion. I noticed this while playing a game. A control+click (which is used heavily in the game) caused the menu to pop up because of the escape key event.

**Comment by timdvail** [comment]
Yeah, this would be really nice.  This is the biggest issue with mapping the left/right shift key to delete/backspace respectively -- you can't do shift-click to select without it also generating a 'delete' key immediately after (or backspace depending on which shift key you used).

**Comment by yut23** [comment]
This was fixed by commit f69c5a3. It has not been included in a release yet, so if you want this fix, you will probably (unless your distro has an xcape-git package) need to compile xcape yourself as detailed in the README.

**Comment by minego** [comment]
Awesome! I can't wait to try it out. Thank you.

**Comment by minego** [comment]
It appears to be working perfectly. Thank you.
