### ISSUE TITLE
Alternate keyboard support

### ISSUE THREAD

**Issue by ChillarAnand** [alols/xcape#71]
xcape works well with standard US keyboard layout. Is there a way to make it work with dvorak latyout?

**Comment by Froziph** [comment]
Correct me if i am wrong, but doesn't Dvorak send the exact same keyboard symbols, they are just physically placed differently? Can't see why this wouldn't work with dvorak without any change. Have you tried? Does it not work?

**Comment by ChillarAnand** [comment]
That is what I was thinking. Unfortunately, it is not working. Is it working for you?

**Comment by timdvail** [comment]
I think what you might be seeing is that when you switch layout (say alt-shift) -- xcape is still using the initial layout.  This is a limitation of xcape -- that if any of the keyboard mapping changes, you really need to kill/restart xcape before it will pick up the new layout.  If Dvorak was your initial layout, then I think this might behave properly for Dvorak, but not for the other.  I'm a Dvorak user too -- and I've noticed this isn't limited to xcape -- this issue happens with some of the other shortcut programs out there -- say I have a shortcut set for Win+T for terminal -- if I switch to QWERTY, I have to continue to use the 'T' as it is in Dvorak for the shortcut.

**Comment by ChillarAnand** [comment]
Excellent catch. Thank you @timdvail
