### ISSUE TITLE
xcape simply not working, Fedora 25 on a VM

### ISSUE THREAD

**Issue by colindjk** [alols/xcape#85]
I have used `xcape` for a while now, however I recently switched to using Fedora in a Virtual Machine. So far I've tried unsuccesfully to use xcape in this new environment.

Basically, I call:
```bash
xcape -e "Control_L=Escape"
```
At which point... nothing happens. 

If I hit the left control and release immediately, the escape key is not "pressed". I tried using `ps` to verify that the process was running. 

```bash
ps -aux | grep xcape
```
output:
``` 
user   2816  0.0  0.0  30816   324 ?        Ssl  19:17   0:00 xcape -e Control_L Escape
```

**Comment by otommod** [comment]
Didn't Fedora 25 turn to Wayland by default?

**Comment by colindjk** [comment]
Oh, didn't realize that that would cause the failure :s.

Sorry about that, should've done some research into Fedora 25 and Wayland. I guess I was confused since my other install of Fedora 25 still works with xcape... welp. Thanks though.
