### ISSUE TITLE
Control to ESC not working with xkbmap

### ISSUE THREAD

**Issue by QiangF** [alols/xcape#86]
After change capslock to control with

    setxkbmap -layout "us(intl)" -option  -option ctrl:nocaps

or

    setxkbmap -layout "us(intl)" -option  -option caps:ctrl_modifier

I tried xcape setting like this

    xcape -e 'Control_R=Escape;Shift_L=Control_L|x;Shift_R=Control_L|c;Alt_L=Alt_L|x;Alt_R=Alt_L|c'&

    xcape -e 'Control_L=Escape;Shift_L=Control_L|x;Shift_R=Control_L|c;Alt_L=Alt_L|x;Alt_R=Alt_L|c'&

Neither works.

**Comment by john2x** [comment]
This works on my setup:

```
 setxkbmap -option 'caps:ctrl_modifier'
 xcape -e 'Control_L=Escape;Control_R=Escape'
```
