### ISSUE TITLE
Mapping Alt_L to slash or Shift_L|slash did not produce any results

### ISSUE THREAD

**Issue by pedrols** [alols/xcape#92]
Also, maping to backslash produced "<"

It's probably some keyboard layout conflict. I'm sorry if this has been covered before, but I didn't find help anywhere. Any help is aprecciated!

**Comment by goedson** [comment]
Are you still able to reproduce this?

I've just tried `xcape -e 'Alt_L=slash' ` on my machine and it worked fine.

**Comment by pedrols** [comment]
@goedson it is working now. I can't remember what fixed it
